spring:
  profiles:
    active: uat

  redis:
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
      max-redirects: 3  # 最大重定向次数

    # 连接池配置
    lettuce:
      pool:
        max-active: 8      # 连接池最大连接数
        max-idle: 8        # 连接池最大空闲连接数
        min-idle: 0        # 连接池最小空闲连接数
        max-wait: 1000ms   # 获取连接的最大等待时间

    # 通用配置
    timeout: 2000ms        # 连接超时时间
    database: 0